{"uuid": "ae52fd15-6b23-4e8b-b4ab-4b24ecc7187b", "children": ["4668afcf-c862-41ae-9755-23bac4d3fdc3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x561cc0834133 <unknown>\n#1 0x561cc0568966 <unknown>\n#2 0x561cc0585a51 <unknown>\n#3 0x561cc058c551 <unknown>\n#4 0x561cc05851b3 <unknown>\n#5 0x561cc05cc025 <unknown>\n#6 0x561cc05cba11 <unknown>\n#7 0x561cc05cd386 <unknown>\n#8 0x561cc05cd18f <unknown>\n#9 0x561cc05c49a3 <unknown>\n#10 0x561cc059946a <unknown>\n#11 0x561cc059a55e <unknown>\n#12 0x561cc07f3cae <unknown>\n#13 0x561cc07f78fe <unknown>\n#14 0x561cc0800f20 <unknown>\n#15 0x561cc07f8923 <unknown>\n#16 0x561cc07cbc0e <unknown>\n#17 0x561cc081bb08 <unknown>\n#18 0x561cc081bc97 <unknown>\n#19 0x561cc082c113 <unknown>\n#20 0x7f2312494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927487686, "stop": 1684927489901}], "start": 1684927487686, "stop": 1684927489925}