{"uuid": "4c473684-4a15-4fde-aab1-a25ac7c0b861", "children": ["930622b7-c6d9-4b3c-a204-6217625f7358"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55ea4df74133 <unknown>\n#1 0x55ea4dca8966 <unknown>\n#2 0x55ea4dcc5a51 <unknown>\n#3 0x55ea4dccc551 <unknown>\n#4 0x55ea4dcc51b3 <unknown>\n#5 0x55ea4dd0c025 <unknown>\n#6 0x55ea4dd0ba11 <unknown>\n#7 0x55ea4dd0d386 <unknown>\n#8 0x55ea4dd0d18f <unknown>\n#9 0x55ea4dd049a3 <unknown>\n#10 0x55ea4dcd946a <unknown>\n#11 0x55ea4dcda55e <unknown>\n#12 0x55ea4df33cae <unknown>\n#13 0x55ea4df378fe <unknown>\n#14 0x55ea4df40f20 <unknown>\n#15 0x55ea4df38923 <unknown>\n#16 0x55ea4df0bc0e <unknown>\n#17 0x55ea4df5bb08 <unknown>\n#18 0x55ea4df5bc97 <unknown>\n#19 0x55ea4df6c113 <unknown>\n#20 0x7fdd00694b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927676498, "stop": 1684927678521}], "start": 1684927676498, "stop": 1684927678558}