{"uuid": "4477a874-362f-43b7-96d7-2269370e7804", "children": ["6e2f3a3c-e794-41ae-ab7d-39d3e78b1962"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5561e29e4133 <unknown>\n#1 0x5561e2718966 <unknown>\n#2 0x5561e2735a51 <unknown>\n#3 0x5561e273c551 <unknown>\n#4 0x5561e27351b3 <unknown>\n#5 0x5561e277c025 <unknown>\n#6 0x5561e277ba11 <unknown>\n#7 0x5561e277d386 <unknown>\n#8 0x5561e277d18f <unknown>\n#9 0x5561e27749a3 <unknown>\n#10 0x5561e274946a <unknown>\n#11 0x5561e274a55e <unknown>\n#12 0x5561e29a3cae <unknown>\n#13 0x5561e29a78fe <unknown>\n#14 0x5561e29b0f20 <unknown>\n#15 0x5561e29a8923 <unknown>\n#16 0x5561e297bc0e <unknown>\n#17 0x5561e29cbb08 <unknown>\n#18 0x5561e29cbc97 <unknown>\n#19 0x5561e29dc113 <unknown>\n#20 0x7fa0cd294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927644964, "stop": 1684927647366}], "start": 1684927644964, "stop": 1684927647401}