{"uuid": "f2ddab25-b034-430e-b1a0-42c8f0e595df", "children": ["d025e30d-3575-4f76-ba77-04f35dc31f14"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5613e053d133 <unknown>\n#1 0x5613e0271966 <unknown>\n#2 0x5613e028ea51 <unknown>\n#3 0x5613e0295551 <unknown>\n#4 0x5613e028e1b3 <unknown>\n#5 0x5613e02d5025 <unknown>\n#6 0x5613e02d4a11 <unknown>\n#7 0x5613e02d6386 <unknown>\n#8 0x5613e02d618f <unknown>\n#9 0x5613e02cd9a3 <unknown>\n#10 0x5613e02a246a <unknown>\n#11 0x5613e02a355e <unknown>\n#12 0x5613e04fccae <unknown>\n#13 0x5613e05008fe <unknown>\n#14 0x5613e0509f20 <unknown>\n#15 0x5613e0501923 <unknown>\n#16 0x5613e04d4c0e <unknown>\n#17 0x5613e0524b08 <unknown>\n#18 0x5613e0524c97 <unknown>\n#19 0x5613e0535113 <unknown>\n#20 0x7fe9e1094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927636630, "stop": 1684927638856}], "start": 1684927636630, "stop": 1684927638880}