{"uuid": "0fd20313-ddfc-4311-a8ce-bde77aeea191", "children": ["8ee91732-2f16-414a-970d-a9ef7d64c6b0"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x565406d1f133 <unknown>\n#1 0x565406a53966 <unknown>\n#2 0x565406a70a51 <unknown>\n#3 0x565406a77551 <unknown>\n#4 0x565406a701b3 <unknown>\n#5 0x565406ab7025 <unknown>\n#6 0x565406ab6a11 <unknown>\n#7 0x565406ab8386 <unknown>\n#8 0x565406ab818f <unknown>\n#9 0x565406aaf9a3 <unknown>\n#10 0x565406a8446a <unknown>\n#11 0x565406a8555e <unknown>\n#12 0x565406cdecae <unknown>\n#13 0x565406ce28fe <unknown>\n#14 0x565406cebf20 <unknown>\n#15 0x565406ce3923 <unknown>\n#16 0x565406cb6c0e <unknown>\n#17 0x565406d06b08 <unknown>\n#18 0x565406d06c97 <unknown>\n#19 0x565406d17113 <unknown>\n#20 0x7f7340c94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927638882, "stop": 1684927641287}], "start": 1684927638882, "stop": 1684927641319}