{"uuid": "cdc4ba18-34db-4ee6-8c3a-9627225e5487", "children": ["27527f0e-cca9-49c1-94f9-c136d614d626"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x562dc3310133 <unknown>\n#1 0x562dc3044966 <unknown>\n#2 0x562dc3061a51 <unknown>\n#3 0x562dc3068551 <unknown>\n#4 0x562dc30611b3 <unknown>\n#5 0x562dc30a8025 <unknown>\n#6 0x562dc30a7a11 <unknown>\n#7 0x562dc30a9386 <unknown>\n#8 0x562dc30a918f <unknown>\n#9 0x562dc30a09a3 <unknown>\n#10 0x562dc307546a <unknown>\n#11 0x562dc307655e <unknown>\n#12 0x562dc32cfcae <unknown>\n#13 0x562dc32d38fe <unknown>\n#14 0x562dc32dcf20 <unknown>\n#15 0x562dc32d4923 <unknown>\n#16 0x562dc32a7c0e <unknown>\n#17 0x562dc32f7b08 <unknown>\n#18 0x562dc32f7c97 <unknown>\n#19 0x562dc3308113 <unknown>\n#20 0x7f3beba94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927647402, "stop": 1684927649610}], "start": 1684927647402, "stop": 1684927649633}