{"uuid": "8e51e3e1-b7f1-4ea9-b6c9-b6d5ceceaeba", "children": ["73020b05-ad24-4167-897d-b06757172556"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x555fd14c2133 <unknown>\n#1 0x555fd11f6966 <unknown>\n#2 0x555fd1213a51 <unknown>\n#3 0x555fd121a551 <unknown>\n#4 0x555fd12131b3 <unknown>\n#5 0x555fd125a025 <unknown>\n#6 0x555fd1259a11 <unknown>\n#7 0x555fd125b386 <unknown>\n#8 0x555fd125b18f <unknown>\n#9 0x555fd12529a3 <unknown>\n#10 0x555fd122746a <unknown>\n#11 0x555fd122855e <unknown>\n#12 0x555fd1481cae <unknown>\n#13 0x555fd14858fe <unknown>\n#14 0x555fd148ef20 <unknown>\n#15 0x555fd1486923 <unknown>\n#16 0x555fd1459c0e <unknown>\n#17 0x555fd14a9b08 <unknown>\n#18 0x555fd14a9c97 <unknown>\n#19 0x555fd14ba113 <unknown>\n#20 0x7fd484a94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927475427, "stop": 1684927478133}], "start": 1684927475427, "stop": 1684927478173}