{"uuid": "4e0785f3-8873-49dc-ba0d-d79c41325d32", "children": ["c6e969d6-2cba-4ef5-9a93-a0ca85bfcb55"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55caf214e133 <unknown>\n#1 0x55caf1e82966 <unknown>\n#2 0x55caf1e9fa51 <unknown>\n#3 0x55caf1ea6551 <unknown>\n#4 0x55caf1e9f1b3 <unknown>\n#5 0x55caf1ee6025 <unknown>\n#6 0x55caf1ee5a11 <unknown>\n#7 0x55caf1ee7386 <unknown>\n#8 0x55caf1ee718f <unknown>\n#9 0x55caf1ede9a3 <unknown>\n#10 0x55caf1eb346a <unknown>\n#11 0x55caf1eb455e <unknown>\n#12 0x55caf210dcae <unknown>\n#13 0x55caf21118fe <unknown>\n#14 0x55caf211af20 <unknown>\n#15 0x55caf2112923 <unknown>\n#16 0x55caf20e5c0e <unknown>\n#17 0x55caf2135b08 <unknown>\n#18 0x55caf2135c97 <unknown>\n#19 0x55caf2146113 <unknown>\n#20 0x7f43a8e94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927483327, "stop": 1684927486736}], "start": 1684927483327, "stop": 1684927486797}