{"uuid": "57e3b1fe-05f6-41e2-8d11-93249a0f79e6", "children": ["d79ffd0a-5dd8-4684-bb0f-3fda30130a4d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55bd08c70133 <unknown>\n#1 0x55bd089a4966 <unknown>\n#2 0x55bd089c1a51 <unknown>\n#3 0x55bd089c8551 <unknown>\n#4 0x55bd089c11b3 <unknown>\n#5 0x55bd08a08025 <unknown>\n#6 0x55bd08a07a11 <unknown>\n#7 0x55bd08a09386 <unknown>\n#8 0x55bd08a0918f <unknown>\n#9 0x55bd08a009a3 <unknown>\n#10 0x55bd089d546a <unknown>\n#11 0x55bd089d655e <unknown>\n#12 0x55bd08c2fcae <unknown>\n#13 0x55bd08c338fe <unknown>\n#14 0x55bd08c3cf20 <unknown>\n#15 0x55bd08c34923 <unknown>\n#16 0x55bd08c07c0e <unknown>\n#17 0x55bd08c57b08 <unknown>\n#18 0x55bd08c57c97 <unknown>\n#19 0x55bd08c68113 <unknown>\n#20 0x7f9ae6e94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927480473, "stop": 1684927482754}], "start": 1684927480473, "stop": 1684927482785}