{"uuid": "49314898-d054-4c4e-8d27-8fa4290728c4", "children": ["a755f036-8ec4-4cfb-bafe-b7ed64e38bad"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5622d0297133 <unknown>\n#1 0x5622cffcb966 <unknown>\n#2 0x5622cffe8a51 <unknown>\n#3 0x5622cffef551 <unknown>\n#4 0x5622cffe81b3 <unknown>\n#5 0x5622d002f025 <unknown>\n#6 0x5622d002ea11 <unknown>\n#7 0x5622d0030386 <unknown>\n#8 0x5622d003018f <unknown>\n#9 0x5622d00279a3 <unknown>\n#10 0x5622cfffc46a <unknown>\n#11 0x5622cfffd55e <unknown>\n#12 0x5622d0256cae <unknown>\n#13 0x5622d025a8fe <unknown>\n#14 0x5622d0263f20 <unknown>\n#15 0x5622d025b923 <unknown>\n#16 0x5622d022ec0e <unknown>\n#17 0x5622d027eb08 <unknown>\n#18 0x5622d027ec97 <unknown>\n#19 0x5622d028f113 <unknown>\n#20 0x7f399ac94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927675236, "stop": 1684927677220}], "start": 1684927675236, "stop": 1684927677250}