{"uuid": "5ef20c34-ca5e-490b-9f9b-4975562d69f0", "children": ["97af9df3-bb3d-444e-8715-eb8e4d05f202"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x560d64738133 <unknown>\n#1 0x560d6446c966 <unknown>\n#2 0x560d64489a51 <unknown>\n#3 0x560d64490551 <unknown>\n#4 0x560d644891b3 <unknown>\n#5 0x560d644d0025 <unknown>\n#6 0x560d644cfa11 <unknown>\n#7 0x560d644d1386 <unknown>\n#8 0x560d644d118f <unknown>\n#9 0x560d644c89a3 <unknown>\n#10 0x560d6449d46a <unknown>\n#11 0x560d6449e55e <unknown>\n#12 0x560d646f7cae <unknown>\n#13 0x560d646fb8fe <unknown>\n#14 0x560d64704f20 <unknown>\n#15 0x560d646fc923 <unknown>\n#16 0x560d646cfc0e <unknown>\n#17 0x560d6471fb08 <unknown>\n#18 0x560d6471fc97 <unknown>\n#19 0x560d64730113 <unknown>\n#20 0x7fcd4ae94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927635771, "stop": 1684927638145}], "start": 1684927635771, "stop": 1684927638169}