{"uuid": "a6f49af2-fc45-43f2-8dca-ea67bd8b3f01", "children": ["8355c4ee-394a-4a50-a703-c59b1b3a58a0"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x562b904ba133 <unknown>\n#1 0x562b901ee966 <unknown>\n#2 0x562b9020ba51 <unknown>\n#3 0x562b90212551 <unknown>\n#4 0x562b9020b1b3 <unknown>\n#5 0x562b90252025 <unknown>\n#6 0x562b90251a11 <unknown>\n#7 0x562b90253386 <unknown>\n#8 0x562b9025318f <unknown>\n#9 0x562b9024a9a3 <unknown>\n#10 0x562b9021f46a <unknown>\n#11 0x562b9022055e <unknown>\n#12 0x562b90479cae <unknown>\n#13 0x562b9047d8fe <unknown>\n#14 0x562b90486f20 <unknown>\n#15 0x562b9047e923 <unknown>\n#16 0x562b90451c0e <unknown>\n#17 0x562b904a1b08 <unknown>\n#18 0x562b904a1c97 <unknown>\n#19 0x562b904b2113 <unknown>\n#20 0x7fd4f1e94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927638652, "stop": 1684927641287}], "start": 1684927638652, "stop": 1684927641319}