{"uuid": "aee4ec1c-938b-401f-a9b7-9714af17aa58", "children": ["bc9eb9a5-6b24-4f52-8fc1-f08482d12bec"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55ecd0ce2133 <unknown>\n#1 0x55ecd0a16966 <unknown>\n#2 0x55ecd0a33a51 <unknown>\n#3 0x55ecd0a3a551 <unknown>\n#4 0x55ecd0a331b3 <unknown>\n#5 0x55ecd0a7a025 <unknown>\n#6 0x55ecd0a79a11 <unknown>\n#7 0x55ecd0a7b386 <unknown>\n#8 0x55ecd0a7b18f <unknown>\n#9 0x55ecd0a729a3 <unknown>\n#10 0x55ecd0a4746a <unknown>\n#11 0x55ecd0a4855e <unknown>\n#12 0x55ecd0ca1cae <unknown>\n#13 0x55ecd0ca58fe <unknown>\n#14 0x55ecd0caef20 <unknown>\n#15 0x55ecd0ca6923 <unknown>\n#16 0x55ecd0c79c0e <unknown>\n#17 0x55ecd0cc9b08 <unknown>\n#18 0x55ecd0cc9c97 <unknown>\n#19 0x55ecd0cda113 <unknown>\n#20 0x7fbddee94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927479786, "stop": 1684927481776}], "start": 1684927479785, "stop": 1684927481825}