{"uuid": "ea8bc695-3fc8-4f6f-a8bb-ae1265abe948", "children": ["30ececa3-51a3-47d1-ad41-b9acc83778e4"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55d067a09133 <unknown>\n#1 0x55d06773d966 <unknown>\n#2 0x55d06775aa51 <unknown>\n#3 0x55d067761551 <unknown>\n#4 0x55d06775a1b3 <unknown>\n#5 0x55d0677a1025 <unknown>\n#6 0x55d0677a0a11 <unknown>\n#7 0x55d0677a2386 <unknown>\n#8 0x55d0677a218f <unknown>\n#9 0x55d0677999a3 <unknown>\n#10 0x55d06776e46a <unknown>\n#11 0x55d06776f55e <unknown>\n#12 0x55d0679c8cae <unknown>\n#13 0x55d0679cc8fe <unknown>\n#14 0x55d0679d5f20 <unknown>\n#15 0x55d0679cd923 <unknown>\n#16 0x55d0679a0c0e <unknown>\n#17 0x55d0679f0b08 <unknown>\n#18 0x55d0679f0c97 <unknown>\n#19 0x55d067a01113 <unknown>\n#20 0x7f51b4694b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927481157, "stop": 1684927483298}], "start": 1684927481157, "stop": 1684927483358}