{"uuid": "cfa06bf8-561d-4eec-8cca-c74c5d559a75", "children": ["af2d46a7-243e-4442-a8f3-b555dc471646"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55d82bdaa133 <unknown>\n#1 0x55d82bade966 <unknown>\n#2 0x55d82bafba51 <unknown>\n#3 0x55d82bb02551 <unknown>\n#4 0x55d82bafb1b3 <unknown>\n#5 0x55d82bb42025 <unknown>\n#6 0x55d82bb41a11 <unknown>\n#7 0x55d82bb43386 <unknown>\n#8 0x55d82bb4318f <unknown>\n#9 0x55d82bb3a9a3 <unknown>\n#10 0x55d82bb0f46a <unknown>\n#11 0x55d82bb1055e <unknown>\n#12 0x55d82bd69cae <unknown>\n#13 0x55d82bd6d8fe <unknown>\n#14 0x55d82bd76f20 <unknown>\n#15 0x55d82bd6e923 <unknown>\n#16 0x55d82bd41c0e <unknown>\n#17 0x55d82bd91b08 <unknown>\n#18 0x55d82bd91c97 <unknown>\n#19 0x55d82bda2113 <unknown>\n#20 0x7f667e294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927675839, "stop": 1684927678132}], "start": 1684927675839, "stop": 1684927678162}