{"uuid": "f318808b-2057-43a8-8c90-e67a1000f6bb", "children": ["8258a06c-a6e4-4ca5-9cc3-61a3556c2840"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55df5d395133 <unknown>\n#1 0x55df5d0c9966 <unknown>\n#2 0x55df5d0e6a51 <unknown>\n#3 0x55df5d0ed551 <unknown>\n#4 0x55df5d0e61b3 <unknown>\n#5 0x55df5d12d025 <unknown>\n#6 0x55df5d12ca11 <unknown>\n#7 0x55df5d12e386 <unknown>\n#8 0x55df5d12e18f <unknown>\n#9 0x55df5d1259a3 <unknown>\n#10 0x55df5d0fa46a <unknown>\n#11 0x55df5d0fb55e <unknown>\n#12 0x55df5d354cae <unknown>\n#13 0x55df5d3588fe <unknown>\n#14 0x55df5d361f20 <unknown>\n#15 0x55df5d359923 <unknown>\n#16 0x55df5d32cc0e <unknown>\n#17 0x55df5d37cb08 <unknown>\n#18 0x55df5d37cc97 <unknown>\n#19 0x55df5d38d113 <unknown>\n#20 0x7ffb85c94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927484091, "stop": 1684927487168}], "start": 1684927484091, "stop": 1684927487218}