{"uuid": "7292deea-c2e1-4b31-9318-e32298070c69", "children": ["569bb7fa-d652-483e-b995-6a53ad559107"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x560ca426f133 <unknown>\n#1 0x560ca3fa3966 <unknown>\n#2 0x560ca3fc0a51 <unknown>\n#3 0x560ca3fc7551 <unknown>\n#4 0x560ca3fc01b3 <unknown>\n#5 0x560ca4007025 <unknown>\n#6 0x560ca4006a11 <unknown>\n#7 0x560ca4008386 <unknown>\n#8 0x560ca400818f <unknown>\n#9 0x560ca3fff9a3 <unknown>\n#10 0x560ca3fd446a <unknown>\n#11 0x560ca3fd555e <unknown>\n#12 0x560ca422ecae <unknown>\n#13 0x560ca42328fe <unknown>\n#14 0x560ca423bf20 <unknown>\n#15 0x560ca4233923 <unknown>\n#16 0x560ca4206c0e <unknown>\n#17 0x560ca4256b08 <unknown>\n#18 0x560ca4256c97 <unknown>\n#19 0x560ca4267113 <unknown>\n#20 0x7f8433294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927638170, "stop": 1684927641036}], "start": 1684927638170, "stop": 1684927641076}