{"uuid": "9604408f-1443-43ea-9a48-85bd59c29d77", "children": ["2ed59e34-a297-4313-9075-bc13f5508209"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5617f3642133 <unknown>\n#1 0x5617f3376966 <unknown>\n#2 0x5617f3393a51 <unknown>\n#3 0x5617f339a551 <unknown>\n#4 0x5617f33931b3 <unknown>\n#5 0x5617f33da025 <unknown>\n#6 0x5617f33d9a11 <unknown>\n#7 0x5617f33db386 <unknown>\n#8 0x5617f33db18f <unknown>\n#9 0x5617f33d29a3 <unknown>\n#10 0x5617f33a746a <unknown>\n#11 0x5617f33a855e <unknown>\n#12 0x5617f3601cae <unknown>\n#13 0x5617f36058fe <unknown>\n#14 0x5617f360ef20 <unknown>\n#15 0x5617f3606923 <unknown>\n#16 0x5617f35d9c0e <unknown>\n#17 0x5617f3629b08 <unknown>\n#18 0x5617f3629c97 <unknown>\n#19 0x5617f363a113 <unknown>\n#20 0x7f0798294b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927642785, "stop": 1684927644901}], "start": 1684927642785, "stop": 1684927644960}