{"uuid": "7bd3e82e-9e45-4454-a059-fa5fef417402", "children": ["ef84ad22-45fe-4a2f-adf7-3cbf6067b91d"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x557d6b730133 <unknown>\n#1 0x557d6b464966 <unknown>\n#2 0x557d6b481a51 <unknown>\n#3 0x557d6b488551 <unknown>\n#4 0x557d6b4811b3 <unknown>\n#5 0x557d6b4c8025 <unknown>\n#6 0x557d6b4c7a11 <unknown>\n#7 0x557d6b4c9386 <unknown>\n#8 0x557d6b4c918f <unknown>\n#9 0x557d6b4c09a3 <unknown>\n#10 0x557d6b49546a <unknown>\n#11 0x557d6b49655e <unknown>\n#12 0x557d6b6efcae <unknown>\n#13 0x557d6b6f38fe <unknown>\n#14 0x557d6b6fcf20 <unknown>\n#15 0x557d6b6f4923 <unknown>\n#16 0x557d6b6c7c0e <unknown>\n#17 0x557d6b717b08 <unknown>\n#18 0x557d6b717c97 <unknown>\n#19 0x557d6b728113 <unknown>\n#20 0x7f275f494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927646046, "stop": 1684927648010}], "start": 1684927646046, "stop": 1684927648036}