{"uuid": "1eca54db-95d0-4dd3-9c29-ea389f0c49bd", "children": ["e5fe2523-e968-4306-b373-21a6ef29f102"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55f4d1db0133 <unknown>\n#1 0x55f4d1ae4966 <unknown>\n#2 0x55f4d1b01a51 <unknown>\n#3 0x55f4d1b08551 <unknown>\n#4 0x55f4d1b011b3 <unknown>\n#5 0x55f4d1b48025 <unknown>\n#6 0x55f4d1b47a11 <unknown>\n#7 0x55f4d1b49386 <unknown>\n#8 0x55f4d1b4918f <unknown>\n#9 0x55f4d1b409a3 <unknown>\n#10 0x55f4d1b1546a <unknown>\n#11 0x55f4d1b1655e <unknown>\n#12 0x55f4d1d6fcae <unknown>\n#13 0x55f4d1d738fe <unknown>\n#14 0x55f4d1d7cf20 <unknown>\n#15 0x55f4d1d74923 <unknown>\n#16 0x55f4d1d47c0e <unknown>\n#17 0x55f4d1d97b08 <unknown>\n#18 0x55f4d1d97c97 <unknown>\n#19 0x55f4d1da8113 <unknown>\n#20 0x7f2dacc94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927640612, "stop": 1684927642637}], "start": 1684927640612, "stop": 1684927642669}