{"uuid": "6409fec3-7a55-4884-ade5-271f7ab05eda", "children": ["b3dd027e-04b8-49c0-b01d-9f766d980edf"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x559e74a4e133 <unknown>\n#1 0x559e74782966 <unknown>\n#2 0x559e7479fa51 <unknown>\n#3 0x559e747a6551 <unknown>\n#4 0x559e7479f1b3 <unknown>\n#5 0x559e747e6025 <unknown>\n#6 0x559e747e5a11 <unknown>\n#7 0x559e747e7386 <unknown>\n#8 0x559e747e718f <unknown>\n#9 0x559e747de9a3 <unknown>\n#10 0x559e747b346a <unknown>\n#11 0x559e747b455e <unknown>\n#12 0x559e74a0dcae <unknown>\n#13 0x559e74a118fe <unknown>\n#14 0x559e74a1af20 <unknown>\n#15 0x559e74a12923 <unknown>\n#16 0x559e749e5c0e <unknown>\n#17 0x559e74a35b08 <unknown>\n#18 0x559e74a35c97 <unknown>\n#19 0x559e74a46113 <unknown>\n#20 0x7f17ff894b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927643641, "stop": 1684927646013}], "start": 1684927643641, "stop": 1684927646043}