{"uuid": "ac38e9b9-d9f7-4690-95fc-54c5f0d6d0d6", "children": ["7757d640-a7dc-4840-acf2-fddc8c67ccd5"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55c359793133 <unknown>\n#1 0x55c3594c7966 <unknown>\n#2 0x55c3594e4a51 <unknown>\n#3 0x55c3594eb551 <unknown>\n#4 0x55c3594e41b3 <unknown>\n#5 0x55c35952b025 <unknown>\n#6 0x55c35952aa11 <unknown>\n#7 0x55c35952c386 <unknown>\n#8 0x55c35952c18f <unknown>\n#9 0x55c3595239a3 <unknown>\n#10 0x55c3594f846a <unknown>\n#11 0x55c3594f955e <unknown>\n#12 0x55c359752cae <unknown>\n#13 0x55c3597568fe <unknown>\n#14 0x55c35975ff20 <unknown>\n#15 0x55c359757923 <unknown>\n#16 0x55c35972ac0e <unknown>\n#17 0x55c35977ab08 <unknown>\n#18 0x55c35977ac97 <unknown>\n#19 0x55c35978b113 <unknown>\n#20 0x7f0c76094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927644079, "stop": 1684927646547}], "start": 1684927644079, "stop": 1684927646580}