{"uuid": "bafa1901-9092-4a73-90bc-5b6f64ce111f", "children": ["44b3c6e3-3cb8-4458-929e-60b517abbbe6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55d52094b133 <unknown>\n#1 0x55d52067f966 <unknown>\n#2 0x55d52069ca51 <unknown>\n#3 0x55d5206a3551 <unknown>\n#4 0x55d52069c1b3 <unknown>\n#5 0x55d5206e3025 <unknown>\n#6 0x55d5206e2a11 <unknown>\n#7 0x55d5206e4386 <unknown>\n#8 0x55d5206e418f <unknown>\n#9 0x55d5206db9a3 <unknown>\n#10 0x55d5206b046a <unknown>\n#11 0x55d5206b155e <unknown>\n#12 0x55d52090acae <unknown>\n#13 0x55d52090e8fe <unknown>\n#14 0x55d520917f20 <unknown>\n#15 0x55d52090f923 <unknown>\n#16 0x55d5208e2c0e <unknown>\n#17 0x55d520932b08 <unknown>\n#18 0x55d520932c97 <unknown>\n#19 0x55d520943113 <unknown>\n#20 0x7f277e494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927636346, "stop": 1684927638447}], "start": 1684927636346, "stop": 1684927638471}