{"uuid": "3113c24f-0b1f-4cce-ac67-fc04924907e9", "children": ["b6dd0c6d-9c6e-46cf-8dcb-bd5cb012e9e3"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x5639b2285133 <unknown>\n#1 0x5639b1fb9966 <unknown>\n#2 0x5639b1fd6a51 <unknown>\n#3 0x5639b1fdd551 <unknown>\n#4 0x5639b1fd61b3 <unknown>\n#5 0x5639b201d025 <unknown>\n#6 0x5639b201ca11 <unknown>\n#7 0x5639b201e386 <unknown>\n#8 0x5639b201e18f <unknown>\n#9 0x5639b20159a3 <unknown>\n#10 0x5639b1fea46a <unknown>\n#11 0x5639b1feb55e <unknown>\n#12 0x5639b2244cae <unknown>\n#13 0x5639b22488fe <unknown>\n#14 0x5639b2251f20 <unknown>\n#15 0x5639b2249923 <unknown>\n#16 0x5639b221cc0e <unknown>\n#17 0x5639b226cb08 <unknown>\n#18 0x5639b226cc97 <unknown>\n#19 0x5639b227d113 <unknown>\n#20 0x7f45f9494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927485132, "stop": 1684927487659}], "start": 1684927485132, "stop": 1684927487684}