{"uuid": "3178e485-c270-441b-beb8-045310f37ed4", "children": ["f21b5888-65b3-4efe-ac7f-a08b422316d6"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55680a7ee133 <unknown>\n#1 0x55680a522966 <unknown>\n#2 0x55680a53fa51 <unknown>\n#3 0x55680a546551 <unknown>\n#4 0x55680a53f1b3 <unknown>\n#5 0x55680a586025 <unknown>\n#6 0x55680a585a11 <unknown>\n#7 0x55680a587386 <unknown>\n#8 0x55680a58718f <unknown>\n#9 0x55680a57e9a3 <unknown>\n#10 0x55680a55346a <unknown>\n#11 0x55680a55455e <unknown>\n#12 0x55680a7adcae <unknown>\n#13 0x55680a7b18fe <unknown>\n#14 0x55680a7baf20 <unknown>\n#15 0x55680a7b2923 <unknown>\n#16 0x55680a785c0e <unknown>\n#17 0x55680a7d5b08 <unknown>\n#18 0x55680a7d5c97 <unknown>\n#19 0x55680a7e6113 <unknown>\n#20 0x7fb5c7094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927479325, "stop": 1684927482008}], "start": 1684927479325, "stop": 1684927482056}