{"uuid": "7352dd3c-ff0c-4f27-8a99-bdee4bb46097", "children": ["0d4453e8-7c85-47ef-bb60-56d35f53cd05"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x56087dcc2133 <unknown>\n#1 0x56087d9f6966 <unknown>\n#2 0x56087da13a51 <unknown>\n#3 0x56087da1a551 <unknown>\n#4 0x56087da131b3 <unknown>\n#5 0x56087da5a025 <unknown>\n#6 0x56087da59a11 <unknown>\n#7 0x56087da5b386 <unknown>\n#8 0x56087da5b18f <unknown>\n#9 0x56087da529a3 <unknown>\n#10 0x56087da2746a <unknown>\n#11 0x56087da2855e <unknown>\n#12 0x56087dc81cae <unknown>\n#13 0x56087dc858fe <unknown>\n#14 0x56087dc8ef20 <unknown>\n#15 0x56087dc86923 <unknown>\n#16 0x56087dc59c0e <unknown>\n#17 0x56087dca9b08 <unknown>\n#18 0x56087dca9c97 <unknown>\n#19 0x56087dcba113 <unknown>\n#20 0x7fe819894b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927633783, "stop": 1684927635971}], "start": 1684927633783, "stop": 1684927636051}