{"uuid": "d89b7e9d-8689-417e-947d-af1dcc91c661", "children": ["d3cbc0a2-6d70-4caa-99e5-f779023a2391"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x558fb8fa0133 <unknown>\n#1 0x558fb8cd4966 <unknown>\n#2 0x558fb8cf1a51 <unknown>\n#3 0x558fb8cf8551 <unknown>\n#4 0x558fb8cf11b3 <unknown>\n#5 0x558fb8d38025 <unknown>\n#6 0x558fb8d37a11 <unknown>\n#7 0x558fb8d39386 <unknown>\n#8 0x558fb8d3918f <unknown>\n#9 0x558fb8d309a3 <unknown>\n#10 0x558fb8d0546a <unknown>\n#11 0x558fb8d0655e <unknown>\n#12 0x558fb8f5fcae <unknown>\n#13 0x558fb8f638fe <unknown>\n#14 0x558fb8f6cf20 <unknown>\n#15 0x558fb8f64923 <unknown>\n#16 0x558fb8f37c0e <unknown>\n#17 0x558fb8f87b08 <unknown>\n#18 0x558fb8f87c97 <unknown>\n#19 0x558fb8f98113 <unknown>\n#20 0x7f4a56e94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927673497, "stop": 1684927676169}], "start": 1684927673497, "stop": 1684927676238}