{"uuid": "e55af207-ee44-4567-9a88-0c14cbc867ef", "children": ["c39684a1-c2e1-4f76-9d90-4e3d222d0154"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x563b605eb133 <unknown>\n#1 0x563b6031f966 <unknown>\n#2 0x563b6033ca51 <unknown>\n#3 0x563b60343551 <unknown>\n#4 0x563b6033c1b3 <unknown>\n#5 0x563b60383025 <unknown>\n#6 0x563b60382a11 <unknown>\n#7 0x563b60384386 <unknown>\n#8 0x563b6038418f <unknown>\n#9 0x563b6037b9a3 <unknown>\n#10 0x563b6035046a <unknown>\n#11 0x563b6035155e <unknown>\n#12 0x563b605aacae <unknown>\n#13 0x563b605ae8fe <unknown>\n#14 0x563b605b7f20 <unknown>\n#15 0x563b605af923 <unknown>\n#16 0x563b60582c0e <unknown>\n#17 0x563b605d2b08 <unknown>\n#18 0x563b605d2c97 <unknown>\n#19 0x563b605e3113 <unknown>\n#20 0x7f4bb1494b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927641079, "stop": 1684927643600}], "start": 1684927641079, "stop": 1684927643638}