{"uuid": "8b60f957-1994-427c-93ee-b301bef6b696", "children": ["9b304e09-65c0-492a-bdd4-148ef4ebe433"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x564ee5d22133 <unknown>\n#1 0x564ee5a56966 <unknown>\n#2 0x564ee5a73a51 <unknown>\n#3 0x564ee5a7a551 <unknown>\n#4 0x564ee5a731b3 <unknown>\n#5 0x564ee5aba025 <unknown>\n#6 0x564ee5ab9a11 <unknown>\n#7 0x564ee5abb386 <unknown>\n#8 0x564ee5abb18f <unknown>\n#9 0x564ee5ab29a3 <unknown>\n#10 0x564ee5a8746a <unknown>\n#11 0x564ee5a8855e <unknown>\n#12 0x564ee5ce1cae <unknown>\n#13 0x564ee5ce58fe <unknown>\n#14 0x564ee5ceef20 <unknown>\n#15 0x564ee5ce6923 <unknown>\n#16 0x564ee5cb9c0e <unknown>\n#17 0x564ee5d09b08 <unknown>\n#18 0x564ee5d09c97 <unknown>\n#19 0x564ee5d1a113 <unknown>\n#20 0x7f0f82a94b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927477675, "stop": 1684927479287}], "start": 1684927477675, "stop": 1684927479322}