{"uuid": "2d76a309-90e6-44c2-8b7f-20b2717e12aa", "children": ["b4f00602-041a-471d-ab59-50ae7f282924"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55daf1756133 <unknown>\n#1 0x55daf148a966 <unknown>\n#2 0x55daf14a7a51 <unknown>\n#3 0x55daf14ae551 <unknown>\n#4 0x55daf14a71b3 <unknown>\n#5 0x55daf14ee025 <unknown>\n#6 0x55daf14eda11 <unknown>\n#7 0x55daf14ef386 <unknown>\n#8 0x55daf14ef18f <unknown>\n#9 0x55daf14e69a3 <unknown>\n#10 0x55daf14bb46a <unknown>\n#11 0x55daf14bc55e <unknown>\n#12 0x55daf1715cae <unknown>\n#13 0x55daf17198fe <unknown>\n#14 0x55daf1722f20 <unknown>\n#15 0x55daf171a923 <unknown>\n#16 0x55daf16edc0e <unknown>\n#17 0x55daf173db08 <unknown>\n#18 0x55daf173dc97 <unknown>\n#19 0x55daf174e113 <unknown>\n#20 0x7f5da5694b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927489447, "stop": 1684927491738}], "start": 1684927489447, "stop": 1684927491761}