{"uuid": "7c443ec7-fb24-47e8-9f8b-5d15623de235", "children": ["1e65e301-b60e-42c1-b992-82e95c5ccf23"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x563a76d09133 <unknown>\n#1 0x563a76a3d966 <unknown>\n#2 0x563a76a5aa51 <unknown>\n#3 0x563a76a61551 <unknown>\n#4 0x563a76a5a1b3 <unknown>\n#5 0x563a76aa1025 <unknown>\n#6 0x563a76aa0a11 <unknown>\n#7 0x563a76aa2386 <unknown>\n#8 0x563a76aa218f <unknown>\n#9 0x563a76a999a3 <unknown>\n#10 0x563a76a6e46a <unknown>\n#11 0x563a76a6f55e <unknown>\n#12 0x563a76cc8cae <unknown>\n#13 0x563a76ccc8fe <unknown>\n#14 0x563a76cd5f20 <unknown>\n#15 0x563a76ccd923 <unknown>\n#16 0x563a76ca0c0e <unknown>\n#17 0x563a76cf0b08 <unknown>\n#18 0x563a76cf0c97 <unknown>\n#19 0x563a76d01113 <unknown>\n#20 0x7f2aea894b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927648130, "stop": 1684927650211}], "start": 1684927648130, "stop": 1684927650239}