{"uuid": "93e41be5-22c6-432c-a86a-e443a24e4ff8", "children": ["188c253d-eb44-4501-b8e1-d50abac44c03"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidArgumentException: Message: invalid argument: cannot parse capability: browserVersion\nfrom invalid argument: cannot be empty\nStacktrace:\n#0 0x55f4806ab133 <unknown>\n#1 0x55f4803df966 <unknown>\n#2 0x55f4803fca51 <unknown>\n#3 0x55f480403551 <unknown>\n#4 0x55f4803fc1b3 <unknown>\n#5 0x55f480443025 <unknown>\n#6 0x55f480442a11 <unknown>\n#7 0x55f480444386 <unknown>\n#8 0x55f48044418f <unknown>\n#9 0x55f48043b9a3 <unknown>\n#10 0x55f48041046a <unknown>\n#11 0x55f48041155e <unknown>\n#12 0x55f48066acae <unknown>\n#13 0x55f48066e8fe <unknown>\n#14 0x55f480677f20 <unknown>\n#15 0x55f48066f923 <unknown>\n#16 0x55f480642c0e <unknown>\n#17 0x55f480692b08 <unknown>\n#18 0x55f480692c97 <unknown>\n#19 0x55f4806a3113 <unknown>\n#20 0x7fbb4b094b43 <unknown>\n\n", "trace": "  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1121, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/_pytest/fixtures.py\", line 893, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/conftest.py\", line 25, in driver\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 277, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 370, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py\", line 435, in execute\n    self.error_handler.check_response(response)\n  File \"/home/andrei/Desktop/code/devops-sandbox/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1684927646752, "stop": 1684927649025}], "start": 1684927646752, "stop": 1684927649058}